<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression Tests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-08-01T15:36:05</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3e167e5f-f868-4137-b550-0afbec1af3ac</testSuiteGuid>
   <testCaseLink>
      <guid>409b5f87-f8a8-4f67-aef7-e9595f3a9d35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Create Issue Test/User should be able to create issue successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85a603bc-fc08-4ed2-bcb5-3c52d620cff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec627c4c-6549-4a01-b9e2-605be351dd4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bba64aa6-0c6f-48f6-9c70-e9b5c15d2110</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3420820c-45c5-4cf3-a50f-05ec17025041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cba50a02-866d-4cec-8ae2-76f54a55bb74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>939a33d6-5dd3-4efc-9305-ab12b281e337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Search Issue Test/User should be able to search and verify issue content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f7d9b1f-ce67-405f-a886-85b26f22388a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1166b920-d85c-4cc3-9b84-452dca5f9e39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4435a514-5a7d-4d5b-93fb-b48d31c306ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests/Search Issue Test/User should be able to search issues with an jql</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff616f97-8cc9-414d-939a-b6878e3db8fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25a483b7-41c4-4eca-a787-d8c4e2a2aaa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests - Copy/Create Issue Test/User should be able to create issue successfully</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45325ee5-a664-4f57-9c26-a54243c6740e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69cdeb04-2753-4e82-a384-39b3f0948cfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>952aaf88-b8ea-42fb-a3a1-d19c1d9d3c80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>348ba98e-b45d-435d-a644-a01bd0e2f959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d6674ea-fd8a-4307-ab62-f975b64982b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c7dfebb-d710-445b-97a7-4ee732be1313</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests - Copy/Search Issue Test/User should be able to search and verify issue content</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25eed5ab-e252-44f3-818e-7519e258d471</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35c942fe-fdfb-42ff-9205-cecfaa2beb2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19f59528-62b7-4302-8741-1686836f8e14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Advance Examples/Tests - Copy/Search Issue Test/User should be able to search issues with an jql</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75dfbcff-e585-4434-8fe5-5e071064b821</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
